# name: CI

# on:
#   push:
#   pull_request:

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - uses: dtolnay/rust-toolchain@stable
#         with:
#           components: rustfmt, clippy

#       - name: Cache cargo registry
#         uses: actions/cache@v4
#         with:
#           path: |
#             ~/.cargo/registry
#             ~/.cargo/git
#             target/
#           key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
#           restore-keys: |
#             ${{ runner.os }}-cargo-

#       - name: Cargo fmt
#         run: cargo fmt --all --check

#       - name: Cargo clippy
#         run: cargo clippy --all-targets --all-features -- -D warnings

#       - name: Cargo test
#         run: cargo test --all

#       - name: Cargo build release
#         run: cargo build --release